Test exit code

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,40 +1,177 @@
 version: 2.1
 
-#orbs:
-#  win: circleci/windows@1.0.0
+aliases:
+  - &check_status_1
+      echo $status_1
+      if [[ $status_1 -eq 0 ]]; then
+        echo "Exit code is 0 - Pass"
+        exit 0
+      elif [[ $status_1 -eq 127 ]]; then
+        echo "Exit code is 127 - Known issue"
+        exit 0
+      else
+        exit 1
+      fi
+
+  - &check_status_2
+      echo $status_2
+      if [[ $status_2 -eq 0 ]]; then
+      echo "Exit code is 0 - Pass"
+      exit 0
+      elif [[ $status_2 -eq 127 ]]; then
+      echo "Exit code is 127 - Known issue"
+      exit 0
+      else
+      exit 1
+      fi
+
 
 commands:
-  test_command:
+  check_exit_code_1:
+    description: Check exit code 1 description
     parameters:
-      gcc_version:
-        type: integer
-        default: 8
+      exit_code:
+        type: string
     steps:
       - run:
-          name: "Test command"
+          name: "Check exit code 1 name"
           command: |
-            echo "Test command"
-            echo "gcc version 0: $(gcc -v)"
-            echo ""
-            echo "gcc version 02: $(g++ -v)"
-            echo "Param: g++-<< parameters.gcc_version >>"
-            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
-            sudo apt update
-            sudo apt remove g++-5 gcc-5
-            if [ << parameters.gcc_version >> == 9 ]; then
-            sudo apt install -y g++-9
-              sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100 --slave /usr/bin/g++ g++ /usr/bin/g++-9
-            elif [ << parameters.gcc_version >> == 8 ]; then
-              sudo apt install -y g++-8
-                sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100 --slave /usr/bin/g++ g++ /usr/bin/g++-8
+            echo "Status: << parameters.exit_code >>"
+            if [[ << parameters.exit_code >> -eq 0 ]]; then
+              echo "Exit code is 0 - Pass"
+              exit 0
+            elif [[ << parameters.exit_code >> -eq 127 ]]; then
+              echo "Exit code is 127 - Known issue"
+              exit 0
             else
-              echo "wrong gcc version"
-            exit 1
+              echo "Unexpected exit code: << parameters.exit_code >> - Fail"
+              exit 1
             fi
-            echo "gcc version 1: $(gcc -v)"
-            echo ""
-            echo "gcc version 2: $(g++ -v)"
           shell: /bin/bash
+
+  check_exit_code_2:
+    description: Check exit code 2 description
+    steps:
+      - run:
+          name: "Check exit code 2 name"
+          command: |
+            echo "Status: $status_4"
+            if [[ $status_4 -eq 0 ]]; then
+              echo "Exit code is 0 - Pass"
+              exit 0
+            elif [[ $status_4 -eq 127 ]]; then
+              echo "Exit code is 127 - Known issue"
+              exit 0
+            else
+              echo "Unexpected exit code: $status_4 - Fail"
+              exit 1
+            fi
+          shell: /bin/bash
+
+  check_exit_code_3:
+    description: Check exit code 3 description
+    steps:
+      - run:
+          name: "Check exit code 3 name"
+          command: |
+            echo "Status: $status_4_1"
+            if [[ $status_4_1 -eq 0 ]]; then
+              echo "Exit code is 0 - Pass"
+              exit 0
+            elif [[ $status_4_1 -eq 127 ]]; then
+              echo "Exit code is 127 - Known issue"
+              exit 0
+            else
+              echo "Unexpected exit code: $status_4_1 - Fail"
+              exit 1
+            fi
+          shell: /bin/bash
+
+  test_command_1:
+    description: Test command 1 description
+    steps:
+      - run:
+          name: "Test command 1 name"
+          command: |
+            date-dfdg
+            echo $status
+            if [[ $status -eq 0 ]]; then
+              echo "Exit code is 0 - Pass"
+              exit 0
+            elif [[ $status -eq 127 ]]; then
+              echo "Exit code is 127 - Known issue"
+              exit 0
+            else
+              echo "Unexpected exit code: $status - Fail"
+              exit 1
+            fi
+          shell: /bin/bash
+
+#  test_command_2:
+#    description: Test command 2 description
+#    steps:
+#      - run:
+#          name: "Test command 2 name"
+#          command: |
+#            date-dfdg
+#            export status_1=$?
+#            <<: *check_status_1
+#          shell: /bin/bash
+#
+#  test_command_2_1:
+#    description: Test command 2 description
+#    steps:
+#      - run:
+#          name: "Test command 2 name"
+#          command: |
+#            date-dfdg
+#            echo "export status_2=$?" >> $BASH_ENV
+#            <<: *check_status_2
+#          shell: /bin/bash
+
+  test_command_3:
+    description: Test command 3 description
+    steps:
+      - run:
+          name: "Test command 3 name"
+          command: |
+            date-dfdg
+            export status_3=$?
+          shell: /bin/bash
+      - check_exit_code_1:
+          exit_code: $status_3
+
+  test_command_3_1:
+    description: Test command 3 description
+    steps:
+      - run:
+          name: "Test command 3 name"
+          command: |
+            date-dfdg
+            echo "export status_3_1=$?" >> $BASH_ENV
+          shell: /bin/bash
+      - check_exit_code_1:
+          exit_code: $status_3_1
+
+  test_command_4:
+    description: Test command 4 description
+    steps:
+      - run:
+          name: "Test command 4 name"
+          command: |
+            date-dfdg
+            export status_4=$?
+      - check_exit_code_2
+
+  test_command_4_1:
+    description: Test command 4 description
+    steps:
+      - run:
+          name: "Test command 4 name"
+          command: |
+            date-dfdg
+            echo "export status_4_1=$?" >> $BASH_ENV
+      - check_exit_code_3
 
 jobs:
   test_1:
@@ -42,15 +179,56 @@ jobs:
       image: ubuntu-1604:201903-01
     steps:
       - run:
-          name: "Test job"
+          name: "Test job 1"
           command: |
             echo "Call test_command"
           shell: /bin/bash
-      - test_command:
-          gcc_version: 7
+      - test_command_1
+
+  test_2:
+    machine:
+      image: ubuntu-1604:201903-01
+    steps:
+      - test_command_2
+
+  test_2_1:
+    machine:
+      image: ubuntu-1604:201903-01
+    steps:
+      - test_command_2_1
+
+  test_3:
+    machine:
+      image: ubuntu-1604:201903-01
+    steps:
+      - test_command_3
+
+  test_3_1:
+    machine:
+      image: ubuntu-1604:201903-01
+    steps:
+      - test_command_3_1
+
+  test_4:
+    machine:
+      image: ubuntu-1604:201903-01
+    steps:
+      - test_command_4
+
+  test_4_1:
+    machine:
+      image: ubuntu-1604:201903-01
+    steps:
+      - test_command_4_1
 
 workflows:
   version: 2
-  test_workspace:
+  test_workflow:
     jobs:
       - test_1
+#      - test_2
+#      - test_2_1
+      - test_3
+      - test_3_1
+      - test_4
+      - test_4_1
